---
title: "Westminster EV Charge Points"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    logo: www/logo.png
    favicon: www/logo.png
    source_code: embed
    css: styles.css
    social: [ "twitter", "facebook", "linkedin" ]
---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)
library(sf)
```

```{r}
west_bord <- sf::read_sf("../../../data/clean_data_files/westminster_boundary_files/London-wards-2018/London-wards-2018_ESRI/London_Ward_CityMerged.shp")
west_bord <- st_transform(west_bord, 4326) 
west_bord <- west_bord %>%
  dplyr::filter(DISTRICT == "City of Westminster")
```

Map {data-icon="glyphicon-flash"}
=======================================================================

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A {.no-title .no-padding}

```{r}
leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  #fitBounds(-0.18, 51.495, -0.13, 51.528) %>%
  addPolygons(data=west_bord, fill=TRUE, fillOpacity = 0.3, opacity = 1, fillColor = "white", weight = 1, color = "black", label=~NAME, popup = ~paste(HECTARES, "Hectares"))

```

About {data-icon="fa-bars"}
=======================================================================

About Page






